spring.application.name=api-produto

spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/meubanco
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect